<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn admin-button</name>
   <tag></tag>
   <elementGuidId>cf4f0379-3b7b-4959-af17-75cc9302623c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='btn admin-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.admin-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Admin area&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd6c6632-c60b-4e5a-85d9-2e7274537ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn admin-button</value>
      <webElementGuid>39cafddc-8ac3-477c-941d-0b22db4d3501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://admin-demo.nopcommerce.com/admin/</value>
      <webElementGuid>c83358a5-c1c4-42b3-afd5-6c5f74f696d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8e60b54b-99a4-45f8-ac58-79dab081d1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Admin area </value>
      <webElementGuid>964f27f8-b095-421a-9bec-9244f5261d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ph-topic&quot;)/div[@class=&quot;page-body page-body-wrapper&quot;]/div[@class=&quot;demo-section-wrapper&quot;]/div[@class=&quot;demo-section&quot;]/div[@class=&quot;demo-image-wrapper&quot;]/div[@class=&quot;demo-img&quot;]/div[@class=&quot;demo-buttons&quot;]/a[@class=&quot;btn admin-button&quot;]</value>
      <webElementGuid>9b17da03-e1a6-4666-a9a4-cf40c090e963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ph-topic']/div[2]/div/div/div[2]/div/div/a</value>
      <webElementGuid>92e28b64-4318-4046-a7e6-8c6be210f57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nopCommerce Store Demo'])[1]/following::a[1]</value>
      <webElementGuid>1273d25c-bce7-4159-ae70-7c0e2806df60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::a[1]</value>
      <webElementGuid>e64e919e-fe03-4f14-944c-469c85260d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frontend'])[1]/preceding::a[1]</value>
      <webElementGuid>d6c2731c-f86b-4c85-be2b-3802f43d5009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://admin-demo.nopcommerce.com/admin/')]</value>
      <webElementGuid>34ef6181-77e7-44bd-9a42-2d8ae9808b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>b71f9236-f9a1-468f-b2af-3adfc07f9298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://admin-demo.nopcommerce.com/admin/' and (text() = ' Admin area ' or . = ' Admin area ')]</value>
      <webElementGuid>369ebd91-a1ab-4100-9222-ca951e53bf7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
